---

- name: install required packages
  apt: pkg={{ item }} state=present
  with_items:
  - git

- name: carbon-relay-ng install check
  register: carbonrelayng_installed_check
  stat: path={{ carbonrelayng_install_dir }}/carbon-relay-ng
  changed_when: not carbonrelayng_installed_check.stat.exists

- name: create carbon-relay-ng user
  user:
    name=carbon-relay-ng
    system=yes
    shell=/bin/false
    state=present

- name: create carbon-relay-ng group
  group:
    name=carbon-relay-ng
    system=yes
    state=present

- name: ensure install directory
  file: path={{ carbonrelayng_install_dir }} state=directory

- name: ensure lib directory
  file: path=/var/lib/carbon-relay-ng state=directory owner=carbon-relay-ng group=carbon-relay-ng

- name: ensure spool directory
  file: path={{ carbonrelayng_spool_dir }} state=directory owner=carbon-relay-ng group=carbon-relay-ng

- name: ensure log directory
  file: path=/var/log/carbon-relay-ng state=directory

- name: ensure golang workspace
  file: path={{ carbonrelayng_golang_workspace }} state=directory
  when: not carbonrelayng_installed_check.stat.exists

- name: fetch carbon-relay-ng repository
  environment:
    GOPATH: "{{ carbonrelayng_golang_workspace }}"
    PATH: "{{ ansible_env.PATH }}:{{ carbonrelayng_golang_workspace }}/bin"
  command: go get -d github.com/graphite-ng/carbon-relay-ng
    creates={{ carbonrelayng_golang_workspace }}/src/github.com/graphite-ng/carbon-relay-ng
  when: not carbonrelayng_installed_check.stat.exists

- name: fetch go-bindata repository and build it
  environment:
    GOPATH: "{{ carbonrelayng_golang_workspace }}"
    PATH: "{{ ansible_env.PATH }}:{{ carbonrelayng_golang_workspace }}/bin"
  command: go get -u github.com/jteeuwen/go-bindata/...
    creates={{ carbonrelayng_golang_workspace }}/src/github.com/jteeuwen/go-bindata
  when: not carbonrelayng_installed_check.stat.exists

- name: make carbon-relay-ng binary
  environment:
    GOPATH: "{{ carbonrelayng_golang_workspace }}"
    PATH: "{{ ansible_env.PATH }}:{{ carbonrelayng_golang_workspace }}/bin"
  command: make
    chdir="{{ carbonrelayng_golang_workspace }}/src/github.com/graphite-ng/carbon-relay-ng"
    creates={{ carbonrelayng_golang_workspace }}/src/github.com/graphite-ng/carbon-relay-ng/carbon-relay-ng
  when: not carbonrelayng_installed_check.stat.exists

- name: copy carbon-relay-ng to install dir
  command: cp {{ carbonrelayng_golang_workspace }}/src/github.com/graphite-ng/carbon-relay-ng/carbon-relay-ng {{ carbonrelayng_install_dir }}
    creates={{ carbonrelayng_install_dir }}/carbon-relay-ng
  when: not carbonrelayng_installed_check.stat.exists

- name: symlink carbon-relay-ng binary to /usr/local/bin
  file:
    src={{ carbonrelayng_install_dir }}/{{ item }}
    dest=/usr/local/bin/{{ item }} state=link
  with_items:
  - carbon-relay-ng

- name: template init file out to init.d
  template:
    src=carbon-relay-ng.init.j2
    dest=/etc/init.d/carbon-relay-ng
    mode="a+x"
  notify:
  - restart carbon-relay-ng

- name: configure carbon-relay-ng
  template:
    src=carbon-relay-ng.ini.j2
    dest=/etc/carbon-relay-ng.ini
  notify:
  - restart carbon-relay-ng